export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const CANCEL_SEARCH_REQUEST = "CANCEL_SEARCH_REQUEST";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const SEARCH_CANCELLED = "SEARCH_CANCELLED";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const CACHE_SEARCH_RESPONSE = "CACHE_SEARCH_RESPONSE";
